/api/app/roles:
  post:
    summary: Crear Rol
    description: |
      # 👤➕ Crear un nuevo rol
    tags:
      - Roles
    security:
      - bearerAuth: []
    requestBody:
      content:
        application/json:
          schema:
            type: object
            required:
              - nombre
              - descripcion
            properties:
              nombre:
                type: string
                description: Nombre único del Rol.
                example: 'Super Admin'
              descripcion:
                type: string
                description: Descripción del Rol.
                example: 'Gestión de Usuarios, Gestión de Roles, Gestión de Permisos Físicos y Visualización de Eventos.'
    responses:
      '201':
        description: Recurso creado exitosamente.
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: true
                message:
                  type: string
                  example: Rol creado con éxito.
      '400':
        description: Error de validación en los datos enviados.
        content:
          application/json:
            schema:
              type: object
              properties:
                success: { type: boolean, example: false }
                message: { type: string }
                issues:
                  type: array
                  items:
                    type: object
                    properties:
                      field: { type: string }
                      message: { type: string }
            examples:
              estructura_invalida:
                summary: 1. Cuerpo JSON inválido
                value:
                  success: false
                  message: 'Error de validación en los datos enviados.'
                  issues:
                    - message: 'La estructura del cuerpo de la solicitud no es válida. Se requiere un objeto JSON.'
              campos_invalidos:
                summary: 2.  Campos Inválidos
                value:
                  success: false
                  message: 'Error de validación en los datos enviados.'
                  issues:
                    - field: 'nombre'
                      message: "El campo 'nombre' es obligatorio y debe ser una cadena de texto."
                    - field: 'descripcion'
                      message: "El campo 'descripcion' es obligatorio y debe ser una cadena de texto."
              longitud_incorrecta:
                summary: 3. Longitud Incorrecta
                value:
                  success: false
                  message: 'Error de validación en los datos enviados.'
                  issues:
                    - field: 'nombre'
                      message: "El campo 'nombre' debe contener al menos 4 caracteres."
                    - field: 'nombre'
                      message: "El campo 'nombre' no puede exceder los 100 caracteres."
                    - field: 'descripcion'
                      message: "El campo 'descripcion' debe contener al menos 4 caracteres."
                    - field: 'descripcion'
                      message: "El campo 'descripcion' no puede exceder los 100 caracteres."
      '401':
        description: Errores de autenticación
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: false
                message:
                  type: string
                  description: Mensaje de error devuelto por la API.
            examples:
              token_expired:
                summary: 1. Token Expirado
                value:
                  success: false
                  message: 'El token ha expirado.'
              token_invalid:
                summary: 2. Token Inválido
                value:
                  success: false
                  message: 'Token inválido.'
              token_not_found:
                summary: 3. Token no encontrado
                value:
                  success: false
                  message: 'Token no proporcionado.'
              unauthenticated_user:
                summary: 4. Usuario no autenticado
                value:
                  success: false
                  message: 'Usuario no autenticado.'
      '403':
        description: Permisos insuficientes
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: false
                message:
                  type: string
                  example: No tienes los permisos necesarios.
      '409':
        description: El recurso ya existe en la base de datos.
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: false
                message:
                  type: string
                  example: Ya se encuentra registrado un rol con ese nombre.
      '500':
        description: Error interno del servidor.
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: false
                message:
                  type: string
                  example: Error interno del servidor.
