/api/app/roles/{id}/users:
  get:
    summary: Obtener Roles de Usuario por ID
    description: |
      # 🔍 Obtener Roles de Usuario por ID
    tags:
      - Roles
    parameters:
      - name: id
        in: path
        required: true
        description: Identificador único (UUID) del Usario a buscar.
        schema:
          type: string
          format: uuid
        example: '550e8400-e29b-41d4-a716-446655440000'
    responses:
      '200':
        description: Lista de roles obtenida exitosamente.
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: true
                message:
                  type: string
                  example: Roles de Usuario obtenidos exitosamente.
                data:
                  type: array
                  items:
                    type: object
                    properties:
                      id:
                        type: string
                        format: uuid
                        example: '7ccd1b1c-319a-4770-9bea-399cf36fa3cc'
                      nombre:
                        type: string
                        example: 'Administrador'
                      descripcion:
                        type: string
                        example: 'Gestión de Usuarios.'
                      creado_el:
                        type: string
                        example: '24/06/2026, 02:06:39 p. m.'
                      actualizado_el:
                        type: string
                        example: '24/06/2026, 02:19:53 p. m.'
      '400':
        description: Error de validación en los datos enviados.
        content:
          application/json:
            schema:
              type: object
              properties:
                success: { type: boolean, example: false }
                message: { type: string }
                issues:
                  type: array
                  items:
                    type: object
                    properties:
                      field: { type: string }
                      message: { type: string }
            examples:
              parametro_id_invalido:
                summary: 1. ID de parámetro inválido (Path)
                value:
                  success: false
                  message: 'Error de validación en los datos enviados.'
                  issues:
                    - field: 'id'
                      message: 'El parametro de la petición no es un UUID válido.'
      '404':
        description: Recurso no encontrado.
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: false
                message:
                  type: string
                  example: El Usuario no se encuentra registrado.
      '500':
        description: Error interno del servidor.
        content:
          application/json:
            schema:
              type: object
              properties:
                success:
                  type: boolean
                  example: false
                message:
                  type: string
                  example: Error interno del servidor.
